### Get single post by slug
GET http://astrowpheadless.local/wp-json/wp/v2/posts?slug=food-on-a-platter&_embed


### Get all posts with embedded featured image
GET http://astrowpheadless.local/wp-json/wp/v2/posts?_fields=author,id,title,excerpt,slug,_links.wp:featuredmedia,_embedded&_embed


### GET all post slugs
GET http://astrowpheadless.local/wp-json/wp/v2/posts?_fields=slug

### GET all users
GET http://astrowpheadless.local/wp-json/wp/v2/users

